# Repositories currently enforced with the SecOps signer group.
blacklist-monitoring:
  signers: [secops]
  dry: false
linters:
  signers: [secops]
  dry: false
tf-drift-mon-scan:
  signers: [secops]
  dry: false
tf-drift-mon-image:
  signers: [secops]
  dry: false
secops_release_sandbox:
  signers: [secops]
  dry: false

# Enable after each repository is ready for signature enforcement.
# action-gh-release:
#   signers: [secops]
#   dry: false
# check-user-permission:
#   signers: [secops]
#   dry: false
# conventional-changelog-action:
#   signers: [secops]
#   dry: false
# create-pull-request:
#   signers: [secops]
#   dry: false
# gh-find-current-pr:
#   signers: [secops]
#   dry: false
# github-pages-action:
#   signers: [secops]
#   dry: false
# hadolint-action:
#   signers: [secops]
#   dry: false
